

import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import "./globals.css";
import CommonLayout from "@/components/common-layout";
import { ClerkProvider } from "@clerk/nextjs";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="">
        {/* <body className={Inter.className}> */}
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
          <Suspense fallback={<Loading />}>
          <CommonLayout  attribute="class"
            defaultTheme="system"/>
      {children}
    

          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
 